# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
- group: IoT-Platform-Admin

stages:
- stage: BuildQa
  displayName: Build and push QA stage
  jobs:
  - job: getVersionNumber
    displayName: get version number
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        npm run build
        VERSION=$(jq '.version' < package.json | sed 's/"//g')
        echo "##vso[task.setvariable variable=version;isOutput=true]$VERSION"
      name: getVersionNumber
  - job: Build
    displayName: Build
    dependsOn: getVersionNumber
    pool:
      vmImage: 'ubuntu-latest'
    variables: 
      versionNumber: $[ dependencies.getVersionNumber.outputs['getVersionNumber.version'] ]
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(versionNumber)
  - job: Tag
    displayName: Git tag version number
    dependsOn: getVersionNumber
    pool:
      vmImage: 'ubuntu-latest'
    variables: 
      versionNumber: $[ dependencies.getVersionNumber.outputs['getVersionNumber.version'] ]
    steps:
    - checkout: self
      persistCredentials: true
    - bash: |
        git config --global user.name "BuildService"
        git config --global user.email "BuildService@houston-inc.com"
        git tag -a $(versionNumber) -m "new version $(versionNumber)" 
        git tag
        git push origin $(versionNumber)
      name: gitTagVersion

- stage: BuilProd
  displayName: Build and push Production stage
  dependsOn: BuildQa
  condition: succeeded()
  jobs:
  - job: getVersionNumber
    displayName: get version number
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        git config --global user.name "BuildService"
        git config --global user.email "BuildService@houston-inc.com"
        git fetch --tags 
        latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
        git checkout $latestTag
        git pull
        npm run build
        echo "##vso[task.setvariable variable=version;isOutput=true]$latestTag"
      name: getVersionNumber
  - job: Build
    displayName: Build
    dependsOn: getVersionNumber
    pool:
      vmImage: 'ubuntu-latest'
    variables: 
      versionNumber: $[ dependencies.getVersionNumber.outputs['getVersionNumber.version'] ]
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(versionNumber)-prod