# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - development

resources:
  - repo: self

variables:
  - group: IoT-Platform-Admin

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: getVersionNumber
        displayName: get version number
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - bash: |
              VERSION=$(git rev-parse --short HEAD)
              echo "##vso[task.setvariable variable=version;isOutput=true]$VERSION"
            name: getVersionNumber
      - job: Build
        displayName: Build
        dependsOn: getVersionNumber
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          versionNumber:
            $[ dependencies.getVersionNumber.outputs['getVersionNumber.version']
            ]
        steps:
          - task: Npm@1
            inputs:
              customEndpoint: Azure artifacts NPM
          - bash: |
              npm install
              npm run build
            name: buildImage
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(versionNumber)
